### ISSUE TITLE
Per app SSL

### ISSUE THREAD

**Issue by s1037989** [jhthorsen/toadfarm#10]
I don't know if this is possible, but nginx for example can have a different SSL cert per vhost.  Is it possible for toadfarm to do similarly?

**Comment by jhthorsen** [comment]
Not that I know of. toadfarm is limited to [listen](https://metacpan.org/pod/Mojo::Server::Daemon#listen), which only allow one SSL cert pr IP/port.

So, it will "just work" if your domain is tied to different IP-addresses, but I don't think it will allow SNI.

**Comment by s1037989** [comment]
Yep, hoping for SNI...  : (

Thanks for the note!

**Comment by jhthorsen** [comment]
Btw... My setup is hypnotoad => [internet] => cloudflare => [internet] => browser. This means that cloudflare fix all the SSL stuff, while I can just load hypnotoad with some non-verified SSL cert, which doesn't care about domains at all.

https://www.cloudflare.com/

**Comment by s1037989** [comment]
Your cloudflare setup method I'm sure is more ideal, but I did some work with Let's Encrypt and created a Toadfarm plugin to assist my efforts.  https://github.com/s1037989/Toadfarm-Plugin-Letsencrypt

Toadfarm Plugin to handle letsencrypt.org domain verifications.  Multi-domain support from Let's Encrypt is great for allowing each of your mounted apps to be configured as traditional virtual hosts where each app has its own unique FQDN.  A multi-domain cert from LE will allow Toadfarm to load with just one cert/key pair and give TLS support to each mounted app.

The documentation is sloppy right now, but it is present which is abnormal for me.  :)

**Comment by s1037989** [comment]
[SNI support now in Mojolicious 6.40!](https://github.com/kraih/mojo/commit/a2469e62196573bf8d60822e07257daac79b4dd8)

Toadfarm requires no updates to take advantage of SNI, correct?  Just supply the updated listen parameters in the Toadfarm script.

**Comment by jhthorsen** [comment]
That is correct.
