### ISSUE TITLE
t/reload.t failing when there is a .git dir

### ISSUE THREAD

**Issue by nicomen** [jhthorsen/toadfarm#13]
When using dh-make-perl:

(But similar errors appeared when doing a git clone)

```
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t  
t/00-basic.t ........ Too late to run CHECK block at /usr/lib/perl5/EV.pm line 123, <DATA> line 2231.  
t/00-basic.t ........ ok  
t/app-class.t ....... ok  
t/basic.t ........... ok  
t/change-user.t ..... ok  
t/command-reload.t .. ok  
t/command-start.t ... ok  
t/command-stop.t .... ok  
t/custom-error.t .... ok  
t/dsl-basic.t ....... ok  
t/dsl-single.t ...... ok  
t/filter.t .......... skipped: TEST_LIVE=1 is required  
t/local-config.t .... Use of uninitialized value $0 in scalar assignment at /usr/share/perl5/Mojo/Server.pm line 46, <DATA> line 2231.  
t/local-config.t .... ok  
t/log.t ............. [Sat May 23 16:02:51 2015] [debug] Reading configuration file "/home/nicomen/projects/Toadfarm-0.61/t/log.conf"  
t/log.t ............. 1/? # Premature connection close  
# Premature connection close  
t/log.t ............. ok  
t/mount-point.t ..... ok  
t/reload.t .......... fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.  
Use '--' to separate paths from revisions, like this:  
'git <command> [<revision>...] -- [<file>...]'  
# Reloading  
t/reload.t .......... 1/?  
#   Failed test 'exact match for content'  
#   at t/reload.t line 46.  
#          got: 'nok  
# '  
#     expected: 'ok  
# '  
t/reload.t .......... 4/?  
#   Failed test 'possible race condition'  
#   at t/reload.t line 51.  
  
#   Failed test 'chdir before git commands'  
#   at t/reload.t line 57.  
#          got: undef  
#     expected: '1'  
  
#   Failed test 'receive USR2 signal'  
#   at t/reload.t line 58.  
#          got: undef  
#     expected: '1'  
# Skip reloading  
  
#   Failed test 'exact match for content'  
#   at t/reload.t line 63.  
#          got: 'nok  
# '  
#     expected: 'ok  
# '  
t/reload.t .......... 10/?  
#   Failed test 'chdir before git commands'  
#   at t/reload.t line 67.  
#          got: undef  
#     expected: '1'  
  
#   Failed test 'receive USR2 signal'  
#   at t/reload.t line 68.  
#          got: undef  
#     expected: '1'  
# Bad payload  
# Status  
# Looks like you failed 7 tests of 19.  
t/reload.t .......... Dubious, test returned 7 (wstat 1792, 0x700)  
Failed 7/19 subtests  
t/rules.t ........... ok  
t/run-as.t .......... skipped: TOADFARM_SUDO_TEST=1  
t/script.t .......... Too late to run CHECK block at /usr/lib/perl5/EV.pm line 123, <DATA> line 2231.  
t/script.t .......... ok  
t/without-rules.t ... 1/? fatal: Not a git repository: '/dev/null/.git'  
t/without-rules.t ... ok  
  
Test Summary Report  
-------------------  
t/reload.t        (Wstat: 1792 Tests: 19 Failed: 7)  
  Failed tests:  3-6, 9-11  
  Non-zero exit status: 7  
Files=19, Tests=184, 11 wallclock secs ( 0.11 usr  0.13 sys +  5.90 cusr  1.30 csys =  7.44 CPU)  
Result: FAIL  
Failed 1/19 test programs. 7/184 subtests failed.  
make[1]: *** [test_dynamic] Error 255  
make[1]: Leaving directory `/home/nicomen/projects/Toadfarm-0.61'  
dh_auto_test: make -j1 test returned exit code 2  
make: *** [build] Error 2  
make: Leaving directory `/home/nicomen/projects/Toadfarm-0.61'  
Cannot create deb package: 'debian/rules build' failed.  
```

**Comment by jhthorsen** [comment]
That's very weird. Not sure what is going on, so I disabled the test.

Will make a new release later today.

Thanks!

**Comment by nicomen** [comment]
it is not THAT weird. I just does not seem to like having .git dir that doesnt match the teats I think.

**Comment by jhthorsen** [comment]
Please elaborate, because I don't get it. Where does this error come from?

> fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.  
> Use '--' to separate paths from revisions, like this:

I always run the tests with a ```.git``` directory which works like a charm for me. And it's not that it doesn't like a .git directory. It used to _requires_ a .git directory to run before I committed aa359ce.

**Comment by nicomen** [comment]
I meant a git directory that doesnt match what you expect in the tests. For instance not having a origin/master. I can make you a few dumps later today, but if you have it, try: dh-make-perl --build --cpan Toadfarm (builds a deb out of a CPAN module) it is originally made for perl-pkg-debian group so it creates a local git repo out of it. But like I mentioned, just cloning from github gave me errors too. If you can explain the intentions of the reload vs git info, I might even be able to come up with a patch. Thanks.

Nicolas Mendoza

----- Reply message -----
Fra: "Jan Henning Thorsen" <notifications@github.com>
Til: "jhthorsen/toadfarm" <toadfarm@noreply.github.com>
Kopi: "Nicolas Mendoza" <mendoza@pvv.ntnu.no>
Emne: [toadfarm] t/reload.t failing when there is a .git dir (#13)
Dato: man., mai 25, 2015 14:30

Please elaborate, because I don't get it. Where does this error come from?


fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.


Use '--' to separate paths from revisions, like this:


I always run the tests with a .git directory which works like a charm for me. And it's not that it doesn't like a .git directory. It used to requires a .git directory to run before I committed aa359ce.

&mdash;

**Comment by jhthorsen** [comment]
Not sure if I care enough, but I'd appreciate a pull request if you do :smile:

**Comment by nicomen** [comment]
Then I need a short explanation on what reload is testing and how it is related to git, please.

Nicolas Mendoza

----- Reply message -----
Fra: "Jan Henning Thorsen" <notifications@github.com>
Til: "jhthorsen/toadfarm" <toadfarm@noreply.github.com>
Kopi: "Nicolas Mendoza" <mendoza@pvv.ntnu.no>
Emne: [toadfarm] t/reload.t failing when there is a .git dir (#13)
Dato: man., mai 25, 2015 14:46

Not sure if I care enough, but I'd appreciate a pull request if you do  

&mdash;
