### ISSUE TITLE
problem with reload plugin when started from init.d

### ISSUE THREAD

**Issue by s1037989** [jhthorsen/toadfarm#16]
This isn't a Toadfarm problem but I wanted to document the issue so that documentation or a workaround could be made.

When I start toadfarm from one of the suggested system start methods such as from init.d the reload program fails, specifically at line 205 where git fetch is called, git fetch fails with no useful output and then the whole reload fails due to an invalid commit.  I've had the same issue when just creating a bash script that runs in cron and does a git fetch to restart the server if something was pulled -- again, git fetch fails silently and doesn't fetch anything so no merge operation can succeed.

I can't find a solution to this at all.

When I add qx(git fetch -vvv origin) to Toadfarm::Plugin::Reload I get:
error: waitpid for rev-list failed: No child processes
error: waitpid for unpack-objects failed: No child processes
fatal: unpack-objects failed
error: waitpid for fetch-pack failed: No child processes

$ uname -a
Linux mojo 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Can Toadfarm::Plugin::Reload be updated so that it's disabled when started at system startup (or started as root if that's the issue) or perhaps a good log message or at least documentation to make people aware of this issue?  The processes are all running as non-root and toadfarm reload doesn't make anything better, either.

**Comment by s1037989** [comment]
Ok, so it seems the issue is that my repo was using the HTTPS method instead of SSH.  Not sure why that is an issue, but simply switching the remote from HTTPS to SSH got rid of the error with the No child processes messages.

Using SSH, line 205 git fetch fails if the system user doesn't have SSH keys generated and the public key installed in Github.

**Comment by jhthorsen** [comment]
Does the repository require user/password when updating over HTTPS? I don't see how it should behave differently between the two transport methods. The git command is simply:

    git fetch <branch>

Starting the server with log level debug, should tell you the exact command that is executed. You can have a look at the logic here:
* https://github.com/jhthorsen/toadfarm/blob/master/lib/Toadfarm/Plugin/Reload.pm#L200
* https://github.com/jhthorsen/toadfarm/blob/master/lib/Toadfarm/Plugin/Reload.pm#L229

**Comment by s1037989** [comment]
No password is needed to pull for the HTTPS transport.  If I do 'git fetch origin' from the CLI it fetches just fine.  But I get the No child processes error when the GitHub webhook triggers.

[Mon May 25 17:40:59 2015] [debug] POST "/reload/14/30/02/04/65"
[Mon May 25 17:40:59 2015] [debug] Routing to a callback
[Mon May 25 17:40:59 2015] [debug] 200 OK (0.012550s, 79.681/s)
[Mon May 25 17:40:59 2015] [info] 10.0.3.1 POST http://webhook.dev.kit.cm/reload/14/30/02/04/65 200 0.0205s
[Mon May 25 17:41:01 2015] [info] Reloading repo my_app, branch master
[Mon May 25 17:41:01 2015] [debug] run(git fetch origin)
[Mon May 25 17:41:02 2015] [debug] run(git log --format=%H -n1 origin/master)
[Mon May 25 17:41:02 2015] [error] Invalid commit: 25d13af4739ea9fea6d4ccc7c5fde740e067ec16 ne 88779d3c45cd8242906f17be9ca8ad6b6ad11324
[Mon May 25 17:41:02 2015] [debug] run(kill -USR2 1101)

If I destroy the local repo from my toadfarm and re-clone it with the SSH transport, everything immediately works as expected.

[Mon May 25 17:45:45 2015] [debug] POST "/reload/14/30/02/04/65"
[Mon May 25 17:45:45 2015] [debug] Routing to a callback
[Mon May 25 17:45:45 2015] [debug] 200 OK (0.014866s, 67.268/s)
[Mon May 25 17:45:45 2015] [info] 10.0.3.1 POST http://webhook.dev.kit.cm/reload/14/30/02/04/65 200 0.0228s
[Mon May 25 17:45:47 2015] [info] Reloading repo my_app, branch master
[Mon May 25 17:45:47 2015] [debug] run(git fetch origin)
[Mon May 25 17:45:48 2015] [debug] run(git log --format=%H -n1 origin/master)
[Mon May 25 17:45:48 2015] [debug] run(git checkout -f -B master origin/master)
[Mon May 25 17:45:48 2015] [info] <<< Branch master set up to track remote branch master from origin.
[Mon May 25 17:45:48 2015] [debug] run(kill -USR2 1153)
