### ISSUE TITLE
t/reload.t failure

### ISSUE THREAD

**Issue by s1037989** [jhthorsen/toadfarm#17]
When I do 'cpanm Toadfarm', installation fails for the following reason:

```
t/mount-point.t ..... ok
fatal: Not a git repository (or any of the parent directories): .git
# Reloading
   {snip... all misleading errors}
# Status
fatal: Not a git repository: '/home/stefan/.cpanm/work/1432566804.14406/Toadfarm-0.62/.git'
# Looks like you failed 7 tests of 19.
t/reload.t .......... 
Dubious, test returned 7 (wstat 1792, 0x700)
Failed 7/19 subtests 
```

The working directory at this point is in ~/.cpanm/work/.... so correct, there are no git repositories there or in any of the parent directories.

How was this intended to work? I can't understand how the tests work to simulate a git repo with a remote defined.

**Comment by jhthorsen** [comment]
Which version is this?

**Comment by s1037989** [comment]
Sorry...  0.62

**Comment by jhthorsen** [comment]
I'm sorry as well, hehe. I managed to ship a file which forced the test to be run.

https://github.com/jhthorsen/toadfarm/blob/aa359ce20c7f9d67836a211deba3aedff50b673e/t/reload.t#L7

**Comment by s1037989** [comment]
Ah nice!  So that test is just for your purposes then?  That makes a lot more sense.

Thanks!

**Comment by jhthorsen** [comment]
Well... I'm not sure how to run it under cpan testers, so it will only run on request for now.
