### ISSUE TITLE
Nginx reverse proxy docs

### ISSUE THREAD

**Issue by robhammond** [jhthorsen/toadfarm#23]
Hi,

I'm not sure the config listed in the BehindReverseProxy docs is correct - I tried it and had no luck at all. With a few tweaks I got it working with this:

```
upstream myapp {
 server 127.0.0.1:8082;
}
server {
        listen 80;
        server_name example.com;

        location / {
                proxy_set_header X-Request-Base https://$host/myapp;
                rewrite ^/myapp/?(.*)$ /$1 break;
                proxy_pass http://myapp;
        }
}
```

Thanks!

**Comment by jhthorsen** [comment]
Could you tell me more exactly what is missing and what went wrong?

**Comment by robhammond** [comment]
Sure more details:

1. Entered config in current docs, and went to domain. Saw the default Nginx welcome screen, no indication of the domain being routed through to Toadfarm
2. Looking at the current example, it relies on a user hitting **example.com/myapp** before being routed to the app
3. After changing the location block, I think the order of the rewrite rule and the proxy_set_header also caused issues, although I'm not 100% sure about that

So with the change above, if you hit example.com, then the rules seem to process correctly.

I'm running Nginx 10.10 on Ubuntu 16.04 if that's of any use, but I don't think that changes anything.

**Comment by robhammond** [comment]
Just re-tested, the order of rewrite rule & proxy_set_header definitely seems to matter.

Running 3 separate domains off Toadfarm I still had some issues. 

I got it working with a simpler config as follows:

```
upstream myapp {
 server 127.0.0.1:8080;
}
        
server {
        listen 80;
        server_name example.com;

        location / {
                proxy_pass http://myapp;

                proxy_set_header Host $host;
        }
}
```

with the toadfarm mount config as:

```
mount "/home/user/appname/script/myapp" => {
	Host => 'example.com',
};
```

**Comment by jhthorsen** [comment]
Does the changes in 4fa8180 do what you expect?
