### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by s1037989** [jhthorsen/toadfarm#7]
/usr/local/bin/toadfarm is deprecated and, along with it it seems, toadfarm.conf.

I couldn't get the doc described here to work
https://github.com/jhthorsen/toadfarm/blob/master/lib/Toadfarm/Plugin/Reload.pm#L31

For me, this worked well:
```
plugin "Toadfarm::Plugin::Reload" => {
  path => '/path/secret',
  repositories => [
    {
      name => 'repo',
      branch => 'master',
      path => '/path',
      remote => 'origin', # defaults to "origin"
    },
  ],
};
```
An issue with the branch advice at https://github.com/jhthorsen/toadfarm/blob/master/lib/Toadfarm/Plugin/Reload.pm#L71

It's good and accurate and helpful documentation except that (I think) it's very common for production code to be in the master branch and therefore to state explicitly that it should not be master is maybe misleading or confusing or worrying?

**Comment by jhthorsen** [comment]
Oh! Totally forgot about it. Thanks.

I think the advice is very good. I often push more often to master than I want the server to reload. Like push, push, push, tag, make a release, push to "running-branch-name", reload.

**Comment by s1037989** [comment]
Ah!  I see what you're doing there with the advice to not use master.  Interesting!  It's like a special "trick" branch whose sole purpose in life is to trigger production server reloads?

**Comment by jhthorsen** [comment]
Yes. I will change the documentation to say "Tip:" or something...

**Comment by s1037989** [comment]
:+1:
